import type { LeadWithRelations } from "@/lib/leads/types";

export function createLeadsCsv(leads: LeadWithRelations[]): string {
  const headers = [
    "Name",
    "Industry",
    "Company Size",
    "Revenue Range",
    "Address",
    "Phone",
    "Website",
    "Campaign",
    "Segment",
    "Batch Code",
    "Batch Status",
    "Recommendation",
    "Compatibility Score",
    "Quality Score",
    "Primary Contact Name",
    "Primary Contact Role",
    "Primary Decision-Maker Role",
    "Decision-Maker Roles",
    "Contact Count",
    "Email",
    "Email Verification",
    "Warmup Score",
    "Sent Count",
    "Open Count",
    "Click Count",
    "Response Count",
    "Bounce Count",
    "Latest Event",
    "Latest Event At",
    "Reasoning",
  ];

  return [
    headers.join(","),
    ...leads.map((lead) =>
      [
        `"${lead.name}"`,
        `"${lead.company?.industry || lead.type || ""}"`,
        `"${lead.company?.companySize || ""}"`,
        `"${lead.company?.revenueRange || ""}"`,
        `"${lead.address || ""}"`,
        `"${lead.phone || ""}"`,
        `"${lead.website || ""}"`,
        `"${lead.campaign?.name || ""}"`,
        `"${lead.segmentName || lead.campaign?.segmentName || ""}"`,
        `"${lead.batch?.code || ""}"`,
        `"${lead.batch?.status || ""}"`,
        `"${lead.recommendation || ""}"`,
        `${lead.compatibilityScore || 0}%`,
        `${lead.qualityScore || 0}%`,
        `"${lead.primaryContact?.fullName || ""}"`,
        `"${lead.primaryContact?.roleTitle || ""}"`,
        `"${lead.primaryDecisionMakerRole || ""}"`,
        `"${((lead.decisionMakerRoles as string[] | null) || []).join(" | ").replace(/"/g, '""')}"`,
        `${lead.contacts.length || 0}`,
        `"${lead.primaryContact?.email || lead.email || ""}"`,
        `"${lead.primaryContact?.emailVerificationStatus || lead.emailVerificationStatus || ""}"`,
        `${lead.warmupScore || 0}%`,
        `${lead.sentCount || 0}`,
        `${lead.openCount || 0}`,
        `${lead.clickCount || 0}`,
        `${lead.responseCount || 0}`,
        `${lead.bounceCount || 0}`,
        `"${lead.events[0]?.type || ""}"`,
        `"${lead.events[0]?.occurredAt ? new Date(lead.events[0].occurredAt).toISOString() : ""}"`,
        `"${lead.reasoning?.replace(/"/g, '""') || ""}"`,
      ].join(","),
    ),
  ].join("\n");
}
