'use client';

import { motion } from 'framer-motion';
import { Sparkles, Map, Zap, Search, Target } from 'lucide-react';
import HeroActions from './HeroActions';

interface LandingPageContentProps {
  user: any;
}

export default function LandingPageContent({ user }: LandingPageContentProps) {
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
      },
    },
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0 },
  };

  return (
    <main className="relative z-10 max-w-7xl mx-auto px-6 pt-20 pb-32">
      <motion.div
        initial="hidden"
        animate="visible"
        variants={containerVariants}
        className="grid grid-cols-1 lg:grid-cols-2 gap-20 items-center mb-32"
      >
        <section className="space-y-10">
          <motion.div variants={itemVariants} className="inline-flex items-center gap-2 px-4 py-2 bg-blue-50 text-blue-600 rounded-full text-xs font-black uppercase tracking-widest border border-blue-100">
            <Sparkles size={14} />
            AI-Powered Intelligence
          </motion.div>

          <motion.h1 variants={itemVariants} className="text-6xl md:text-7xl font-black text-slate-900 leading-[1.05] tracking-tight">
            Turn Google Maps into your <span className="bg-clip-text text-transparent bg-gradient-to-r from-blue-600 to-indigo-600">Growth Engine.</span>
          </motion.h1>

          <motion.p variants={itemVariants} className="text-xl text-slate-500 leading-relaxed max-w-lg">
            Scrape high-precision business leads and use advanced AI to verify compatibility automatically. Stop cold calling, start closing.
          </motion.p>

          <HeroActions user={user} />
        </section>

        <motion.div
          variants={itemVariants}
          className="relative"
        >
          <div className="absolute -inset-4 bg-gradient-to-tr from-blue-100 to-indigo-100 rounded-[3rem] blur-2xl opacity-50 animate-pulse" />
          <div className="relative bg-white border border-slate-200 rounded-[2.5rem] p-10 shadow-2xl overflow-hidden group">
             <div className="space-y-6">
                {[
                  { color: 'bg-blue-600', icon: <Map size={20} />, title: 'Smart Targeting', desc: 'Precise geo-fencing and category filtering.' },
                  { color: 'bg-indigo-600', icon: <Sparkles size={20} />, title: 'AI Verification', desc: 'GPT-5 Nano checks if they need your help.' },
                  { color: 'bg-slate-900', icon: <Zap size={20} />, title: 'Batch Processing', desc: 'Process 100+ prospects in seconds.' },
                ].map((feat, i) => (
                  <motion.div
                    key={i}
                    whileHover={{ x: 10 }}
                    className="flex items-center gap-6 p-6 rounded-2xl bg-slate-50 border border-slate-100 transition-all hover:bg-white hover:shadow-lg group"
                  >
                     <div className={`w-14 h-14 ${feat.color} rounded-xl flex items-center justify-center text-white shadow-lg`}>
                       {feat.icon}
                     </div>
                     <div>
                       <div className="font-black text-slate-800 text-lg">{feat.title}</div>
                       <div className="text-slate-500 text-sm font-medium">{feat.desc}</div>
                     </div>
                  </motion.div>
                ))}
             </div>
          </div>
        </motion.div>
      </motion.div>

      {/* Workflow Section */}
      <section className="pt-24 border-t border-slate-100">
        <div className="text-center mb-16 space-y-4">
          <h2 className="text-sm font-black text-blue-600 uppercase tracking-[0.3em]">The Workflow</h2>
          <p className="text-4xl font-extrabold text-slate-900 tracking-tight">Four steps to high-intent leads.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          {[
            { num: '01', title: 'Target', desc: 'Define your ideal business categories and target locations.', icon: <Target className="text-blue-600" /> },
            { num: '02', title: 'Scrape', desc: 'Extract live data from Google Maps with deep precision.', color: 'bg-blue-50', icon: <Search className="text-blue-600" /> },
            { num: '03', title: 'Enhance', desc: 'AI analyzes compatibility against your specific goals.', active: true, icon: <Sparkles className="text-indigo-600" /> },
            { num: '04', title: 'Connect', desc: 'Reach out with personalized hooks generated by AI.', icon: <Zap className="text-slate-900" /> },
          ].map((step, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
              className={`p-10 rounded-[2rem] border transition-all hover:shadow-xl ${
                step.active ? 'bg-indigo-600 text-white border-indigo-500 shadow-2xl shadow-indigo-100 scale-105' : 'bg-slate-50 border-slate-100 text-slate-900 hover:bg-white'
              }`}
            >
              <div className={`text-4xl font-black mb-6 opacity-20 ${step.active ? 'text-white' : 'text-slate-900'}`}>{step.num}</div>
              <div className="font-black text-xl mb-4 tracking-tight">{step.title}</div>
              <p className={`text-sm font-medium leading-relaxed ${step.active ? 'text-indigo-100' : 'text-slate-500'}`}>
                {step.desc}
              </p>
            </motion.div>
          ))}
        </div>
      </section>
    </main>
  );
}
