'use client';

import { motion } from 'framer-motion';
import { Target, Search, Sparkles, Zap } from 'lucide-react';

export function WorkflowSection() {
  return (
    <section className="pt-24 border-t border-slate-100">
      <div className="text-center mb-16 space-y-4">
        <h2 className="text-sm font-black text-blue-600 uppercase tracking-[0.3em]">The Workflow</h2>
        <p className="text-4xl font-extrabold text-slate-900 tracking-tight">Four steps to high-intent leads.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
        {[
          {
            num: '01',
            title: 'Target',
            desc: 'Define your ideal business categories and target locations.',
            icon: <Target className="text-blue-600" />,
          },
          {
            num: '02',
            title: 'Source',
            desc: 'Gather verified business data via licensed providers and public records.',
            color: 'bg-blue-50',
            icon: <Search className="text-blue-600" />,
          },
          {
            num: '03',
            title: 'Enhance',
            desc: 'AI analyzes compatibility against your specific goals.',
            active: true,
            icon: <Sparkles className="text-indigo-600" />,
          },
          {
            num: '04',
            title: 'Connect',
            desc: 'Reach out with personalized hooks generated by AI.',
            icon: <Zap className="text-slate-900" />,
          },
        ].map((step, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: i * 0.1 }}
            className={`p-10 rounded-[2rem] border transition-all hover:shadow-xl ${
              step.active
                ? 'bg-indigo-600 text-white border-indigo-500 shadow-2xl shadow-indigo-100 scale-105'
                : 'bg-slate-50 border-slate-100 text-slate-900 hover:bg-white'
            }`}
          >
            <div className={`text-4xl font-black mb-6 opacity-20 ${step.active ? 'text-white' : 'text-slate-900'}`}>{step.num}</div>
            <div className="font-black text-xl mb-4 tracking-tight">{step.title}</div>
            <p className={`text-sm font-medium leading-relaxed ${step.active ? 'text-indigo-100' : 'text-slate-500'}`}>{step.desc}</p>
          </motion.div>
        ))}
      </div>
    </section>
  );
}
